# demo pipleline script in gitlab ci/cd 
stages:
  - build
  - test
  - deploy

# Build job
build-job:
  stage: build
  tags:
    - ci/cd  # This job will run on the runner with the 'ci/cd' tag
  script:
    - echo "Hello, $GITLAB_USER_LOGIN!"

# Test job 1
test-job1:
  stage: test
  tags:
    - ci/cd  # This job will run on the runner with the 'ci/cd' tag
  script:
    - echo "This job tests something"

# Test job 2
test-job2:
  stage: test
  tags:
    - ci/cd  # This job will run on the runner with the 'ci/cd' tag
  script:
    - echo "This job tests something, but takes more time than test-job1."
    - sleep 20

# Deploy job
deploy-prod:
  stage: deploy
  tags:
    - ci/cd  # This job will run on the runner with the 'ci/cd' tag
  script:
    - echo "Deploying to production"
